export const GET_TODO_REQUEST ="GET_TODO_REQUEST"
export const GET_TODO_SUCCESS ="GET_TOTO_SUCCESS"
export const GET_TODO_FAILURE ="GET_TOTO_FAILURE"


export const POST_TODO_REQUEST ="POST_TODO_REQUEST"
export const POST_TODO_SUCCESS ="POST_TOTO_SUCCESS"
export const POST_TODO_FAILURE ="POST_TOTO_FAILURE"
